---

- hosts: localhost
  connection: local
  gather_facts: true
  become: yes

# Exclude 1.5.1  - failing...need to work out why
# Also excluded 1.8  - forced updates and security patches
# 2.2.1.(1,2) Ensure time synchronisation is in use - NOT SCORED -> not relevant to Docker as all time is grabbed from CCoE provided Docker host.
# 4.2.1.(1,3,5) - exclude rsyslog svc restart - SCORED -> Will need to get this sorted at some point.
# 5.2.2->16 - ALL SSH - SCORED - we do not use SSH to connect to the server. We use `docker exec -it XXXX bash`...so not required.


# LEVEL-2.yml includes hashed off!!
  vars:
    cis_level_1_exclusions:
      - 1.1.18
      - 1.5.1
      - 1.5.2
      - 1.5.4
      - 1.8
      - 2.1.11
      - 2.2.1.1
      - 2.2.1.2
      - 3.1.1
      - 3.1.2
      - 3.2.1
      - 3.2.2
      - 3.2.3
      - 3.2.4
      - 3.2.5
      - 3.2.6
      - 3.2.7
      - 3.4.2
      - 3.4.3
      - 4.2.1.1
      - 4.2.1.3
      - 4.2.1.5
      - 5.1.1
      - 5.2.1
      - 5.2.2
      - 5.2.3
      - 5.2.4
      - 5.2.5
      - 5.2.6
      - 5.2.7
      - 5.2.8
      - 5.2.9
      - 5.2.10
      - 5.2.11
      - 5.2.12
      - 5.2.13
      - 5.2.14
      - 5.2.15
      - 5.2.16
      - 5.3.2
      - 5.3.3
      - 5.3.4
    cis_pass_max_days: 45
    cis_umask_default: 002

  roles:
    - Ansible-RHEL7-CIS-Benchmarks
